AWSTemplateFormatVersion: 2010-09-09
Description: Example of Password Generator

Parameters:
  PasswordGeneratorLambdaName:
    Description: Password Generator Lambda name
    Type: String

Resources:

  SimplePassword:
    Type: Custom::Password
    Version: '1.0'
    Properties:
      ServiceToken: !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function', !Ref PasswordGeneratorLambdaName ]]

  MemorablePassword:
    Type: Custom::Password
    Version: '1.0'
    Properties:
      ServiceToken: !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function', !Ref PasswordGeneratorLambdaName ]]
      Memorable: true

  StrongPassword:
    Type: Custom::Password
    Version: '1.0'
    Properties:
      ServiceToken: !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function', !Ref PasswordGeneratorLambdaName ]]
      Strong: true

  CustomPassword:
    Type: Custom::Password
    Version: '1.0'
    Properties:
      ServiceToken: !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function', !Ref PasswordGeneratorLambdaName ]]
      Length: 12
      UppercaseMinCount: 3
      LowercaseMinCount: 3
      NumberMinCount: 2
      SpecialMinCount: 2

Outputs:
  SimplePasswordResult:
    Value: !Ref SimplePassword
  MemorablePasswordResult:
    Value: !Ref MemorablePassword
  StrongPasswordResult:
    Value: !Ref StrongPassword
  CustomPasswordResult:
    Value: !Ref CustomPassword
