language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: m2WhoQ97eCUm3zw2EaSle2v0ske17dJH4czmBM7e83x4G02FJQ2oP5C587TZL5rRsvC6JlLCT4/ITeRsfZfNURxIIPDUbg3QSycrbic/Ri8lt0FmFdMgzmeq2d1XK7k+Mc/rhUa3W0qfrrWeykSc/zha/0cb53nol+y1Xtbiwxu4lHHpBbKZyPKz0xEr4UYuJjAeraHsq2lRzKwsznA+KyyDXUoH/Zb66wyXbTlbhAlJIRZkIRPtdicIOwm2f96Gz6/VCcUrz9nmQhhuHauIFG7ZK8PAOR/MqbmlBxkZI2gAFKMnjOJe9am+6Dt9cxJxt+sQt1yYzELm5v7UBuuOg9R0FigUnWIGV/clrPJkLO5RmVrAus4KaZe3rVK0gwRNND3Kl8b4YVWlt6xcVz0P1Rn3gE2mu9MdfHEOdkRghukO+4XE4VWXc3w8TIJ4RNHTZQ7G3nZ+xB6KKCfcyh7Z8CCc/OB0GAHW+k4KvaDqA8phZh74fOljcXNJi3VmneYVBq5jRLkLUNEKXqqwbXz00AXgT2EQBZTWhM58nTOCzHMc1KPfRGsaZk7nN0cFRjTuii/XJcxXaRUPT1SN0LmU9pS6S+x0RqHfGANUT0SqmzO7Pvrmft0uwAEHA2sJeuZlmTpTugY7Oo1EPsQdEl9fZy3D0exiQJDHAmyxZpKXTZc=
  - secure: gxbml8QtRbFEZP8htCwBjB9yZAvkXGyW7Z9JZh9iJuLg/LxoEn8rsnhPUTm7Dz7+rL54mpQ6yDfbNRnmrPVJETWAFvY9gV20Zjwco9IIPSxuKNxRR4bzUB/HbAVrX2YVCy1lEqOYdVv2kaYeFTgUyIjjRryzgfpneswdSU/O2hYOm3ZfjZrJSFki5fPtqV5EmtMLRkU1DUXhXKYx4QD36opbKZSXrLwX8bA5obi5nd13CuTlzlA1zGqyPtjMMQEK161ZmV0XqqeOHAEXLmuQdBPxAOauTLixnvDkabrwZG0H2UrftCH60wq9cLgfQZg7H6ckA7OAVGE8oBrw62MdA5N78Mc9ouQAgJwKyVpWTkbasBPO0ZC6wQqYbAoLuWk+yVCmQBDBihVsRM3JZ9HS31d49Q7WpJY4s8WPLxpY6g7NuuS0uJYe5b6/l/42Msbc95+Vgje7Cbmdd52Bh5IU1cyWpj/hDwiVOpJwopl0OIbV3OfNqcQ+QW9qICWFiJxvLsBkkzhduOk6x9NAYXvt2bCVs8HKiy2Bcmk0PHGCxrlyFlMfQLWdmVS6iD57LQu9pF/00InSNW9w8ULLbGhm7hAbKYnfYZRUSyfi7Z6K79aVE6J0JERVQ5XnqbH55/hPF+NBUdiEXH0vmHsJwPfFyBIhR1Ki7nb2/SbrCmJgvcY=
  - secure: bFWTCgSxDMBRwMd6LZtu3GgOcdWQgorFehVHP855Mjm7gsFR7O26tSSCd0un0m+Sgc/XYtB/RyshgC+eAoTUmY5oEA/SVfRzEjIAkJOkySheQ/PA8tdAI41EPgmwBU4/ZIfG/o3sbgINjqUvP10lumNVQbthVNsR9A/1Ohjq7GZQk2/7fgKsktGeC+wHRUJH5Szqq/Q35n5HH9q2qynb86fN9RwY7cyDhMpPjk68mQiUCgmwvoALW14+1fEYK/Ld2P7wQtgPq8BMls/thkJaU2VqF6Tp9R6ha/1WakspUXpKCk41KY43YIlu5hvZqQwAraDWiVV8AOTFgCjS55kbySHI/G6VpwU1cVkhEOIhZ4brm7JkYqzKHsra+oNVrPk8gverbkGv4/XVfcZJw/Z7FNRKbUupDksuMJSneJElm/UIVD/R3M1GCkMP5UHTCQ3sriDfZVVmX8a+ZgxrEacY0AJkdpnbDATDT2ijnhFyFdrpm0ZvYYA5M2b0mKfMOYyGGcgx/Nmxdn95iFTzuN9WCI7ImyJxAxFTG6XzzxSEdU18yAUenjyafWdc79g+gs2EsU/ZH7GjoayPvAD7d9adzwBOsi4gV9d69mEU9gPE9kmFKdU7tZ7Ui1R/ar9dz9bd/lPkxIHn0+uzm7OOEqASI/nhuRQEYt6DtZKwuCDhuu8=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
